# galaxy.yml
# ==========
#
# Copying
# -------
#
# Copyright (c) 2022 universe.common authors and contributors.
#
# This file is part of the *universe.common* project.
#
# *universe.common* is a free software project. You can redistribute it and/or
# modify it following the terms of the MIT License.
#
# This software project is distributed *as is*, WITHOUT WARRANTY OF ANY KIND;
# including but not limited to the WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE and NONINFRINGEMENT.
#
# You should have received a copy of the MIT License along with
# *universe.common*. If not, see <http://opensource.org/licenses/MIT>.
#
namespace: "universe"
name: "common"
description: "A general purpose set of Ansible modules."
version: "0.1.2"
readme: "README.md"
authors:
  - "See AUTHORS.rst"
license_file: "LICENSE.rst"
tags:
  - "ansible"
  - "filter"
  - "general"
  - "plugin"
  - "tools"
repository: "https://github.com/x237net/ansible-universe-common"
issues: "https://github.com/x237net/ansible-universe-common/issues"
build_ignore:
  - ".*"
  - "*.lock"
  - "**/.*"
  - "**/*.lock"
  - "changelogs/fragments"
  - "changelogs/fragments/*/**"
  - "pyproject.toml"
